### PR TITLE
Print the error message from the environment configuration scripts at once

### PR DESCRIPTION
**Pull request by pzhlkj6612**
Here are two examples to show the difference before and after this change.

<details>
<summary>Example 1</summary>

## Parameters

- sdk: A
- arch: x64

### Before

> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:vcvarsall.bat] Invalid argument found : A
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; Could not setup Developer Command Prompt: invalid parameters
> 
> ---
> 

### After

> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; Could not setup Developer Command Prompt: invalid parameters [ERROR:vcvarsall.bat] Invalid argument found : A
> 
> ---
> 

### Before

```
...
Error: [ERROR:vcvarsall.bat] Invalid argument found : A
Error: Could not setup Developer Command Prompt: invalid parameters
...
```

### After

```
...
Error: Could not setup Developer Command Prompt: invalid parameters
[ERROR:vcvarsall.bat] Invalid argument found : A
...
```

</details>

<details>
<summary>Example 2</summary>

## Parameters

- sdk: 10.0.10240.0
- arch: x64

### Before

> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:winsdk.bat] Windows SDK 10.0.10240.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um' not found or was incomplete
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] Where [value] is:
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] 1 : basic debug logging
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] 2 : detailed debug logging
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] 3 : trace level logging. Redirection of output to a file when using this level is recommended.
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
> 
> ---
> 
> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
> 
> ---
> 

As you can see, they are too much. And I have no idea why "Could not setup Developer Command Prompt: invalid parameters" is not here.

### After

> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; Could not setup Developer Command Prompt: invalid parameters [ERROR:winsdk.bat] Windows SDK 10.0.10240.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um' not found or was incomplete [ERROR...
> 
> &nbsp;&nbsp;&nbsp;&nbsp; show more
> 
> ---
> 

> (X) <job_name>
> &nbsp;&nbsp;&nbsp;&nbsp; Could not setup Developer Command Prompt: invalid parameters
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:winsdk.bat] Windows SDK 10.0.10240.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um' not found or was incomplete
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] Where [value] is:
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat]    1 : basic debug logging
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat]    2 : detailed debug logging
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
> &nbsp;&nbsp;&nbsp;&nbsp; [ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
> 
> &nbsp;&nbsp;&nbsp;&nbsp; show less
> 
> ---
> 

### Before

```
...
Error: [ERROR:winsdk.bat] Windows SDK 10.0.10240.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um' not found or was incomplete
Error: [ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
Error: [ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
Error: [ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
Error: [ERROR:VsDevCmd.bat] Where [value] is:
Error: [ERROR:VsDevCmd.bat]    1 : basic debug logging
Error: [ERROR:VsDevCmd.bat]    2 : detailed debug logging
Error: [ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
Error: [ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
Error: [ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
Error: Could not setup Developer Command Prompt: invalid parameters
...
```

### After

```
...
Error: Could not setup Developer Command Prompt: invalid parameters
[ERROR:winsdk.bat] Windows SDK 10.0.10240.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um' not found or was incomplete
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
...
```

</details>

### CODE REVIEW

**Review by ilammy — APPROVED** [review]
Makes sense 👍

The change needs some rebasing on the latest `master`, but otherwise looks good.

**Comment by pzhlkj6612** [comment]
Oh no, I did a wrong conflict resolution.

**Comment by pzhlkj6612** [comment]
Thank you for editing the text content. It should be collapsed it by default.

And I'm sorry I didn't make the progress smooth, please squash all the commits into one commit to avoid an ugly history.

**Review by ilammy — APPROVED** [review]

**Comment by ilammy** [comment]
@pzhlkj6612, no worries. As long as it applies cleanly, it's good.

I more or less default to squash-merging anyway unless there is a particular reason to do otherwise.

Thank you for your contributions!

**Pull request merged**
