### PR TITLE
chore: add buildtools edition

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi! Your Git history looks not so good (This branch is 19 commits ahead, 1 commit behind ilammy:master). Maybe a `git rebase a742a854f54111d83b78e97091b5d85ccdaa3e89` command can solve it.

**Comment by qkdreyer** [comment]
@pzhlkj6612 done!

**Comment by pzhlkj6612** [comment]
Hi @qkdreyer , I have a question: how do you test your change? In GitHub's runner, this action is able to find the Enterprise edition of Visual Studio and will not try other editions. Are you using a self-hosted runner?

**Comment by qkdreyer** [comment]
yeah using a self hosted runner and installed using chocolatey : https://community.chocolatey.org/packages/visualstudio2019buildtools

**Comment by qkdreyer** [comment]
using https://github.com/qkdreyer/msvc-dev-cmd/releases/tag/v1-buildtools

image

**Review by pzhlkj6612 — APPROVED** [review]
Looks good to me!

**Comment by qkdreyer** [comment]
@ilammy

**Comment by qkdreyer** [comment]
can we merge that?

**Comment by ilammy** [comment]
Sorry for taking so long 🙇

**Pull request merged**
